### PR TITLE
kdl_parser: switch from TinyXML to TinyXML2

### PR DESCRIPTION
**Pull request by rojkov**
The library TinyXML is considered to be unmaintained and
since all future development is focused on TinyXML2 this
patch updates kdl_parser to use TinyXML2.

This is a followup from https://github.com/ros/kdl_parser/pull/2

### CODE REVIEW

**Comment by sloretz** [comment]
@clalancette I made changes to this PR similar to ros/urdf#9. Would you mind reviewing to check for mistakes?

Side note, I think `urdf::Model::initXml(tinyxml2::XMLDocument *)` could take a `const` document. I'll make a PR for that.

**Review by clalancette — COMMENTED** [review]
This generally looks OK to me.  My one comment has to do with whether `treeFromXml` should take a `tinyxml2::XMLDocument &`, or a `tinyxml2::XMLDocument *`.  Let's resolve that question over in https://github.com/ros/urdf/pull/14, then we can apply the same policy here.

**Comment by clalancette** [comment]
@sloretz I've now changed this to have const pointers like urdf does.  While I was at it, I changed the tinyxml1 version of the API to use the urdf `initString` method to get rid of a deprecation warning in here.  I'm now happy with this, but another review from you to make sure you agree with these changes would be appreciated.  Thanks!

**Review by sloretz — APPROVED** [review]

**Comment by sloretz** [comment]
@rojkov Thanks for the pull request!

**Pull request merged**
