### PR TITLE
Add in a LICENSE file.

### PR DESCRIPTION
**Pull request by clalancette**
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

### CODE REVIEW

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16895/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11465/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17298/)

**Comment by cottsay** [comment]
The license text references a copyright holder, and I've typically seen the 3-clause BSD license include the copyright lines at the beginning. Is there a particular reason to omit it here?

**Comment by clalancette** [comment]
> The license text references a copyright holder, and I've typically seen the 3-clause BSD license include the copyright lines at the beginning. Is there a particular reason to omit it here?

You bring up a good point, which caused me to examine a couple of different things.

First of all, the copyright checking in this package was disabled.  That means we didn't even know if this file conformed to the LICENSE style as laid out in `ament_copyright`.  I've now fixed that in 1fb1d3d .

The second thing I did was to check out what other BSD-style LICENSE files around our codebase looked like.  To summarize, I found the following:

1. LICENSE file that has no copyright holder, and no mention of "BSD License" at the top (like this PR): 4 repositories
2. LICENSE file that has no copyright holder, but has a mention of "BSD License" at the top: 2 repositories
3. LICENSE file that has copyright holders and a mention of "BSD License" at the top: 10 repositories

Apparently our linting accepts all 3 styles, so it is not a problem for linting.  As for what it should look like, I actually think style 2 is the best, as it is a LICENSE file, not a copyright notice.  That said, it looks like the bulk of what we have does include both the "BSD License" and the copyright holders, so I'll switch this one to go with the majority there.

**Review by cottsay — APPROVED** [review]

**Comment by clalancette** [comment]
CI again:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16900/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11471/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17305/)

**Pull request merged**
